In [1]:
import numpy as np

In [3]:
a = np.zeros([4,4])
print a

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [6]:
print '`a` memory location:',a.ctypes.data

`a` memory location: 4302962352


In [10]:
b = np.ones([4,4])
print b

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [11]:
print '`b` memory location:',b.ctypes.data

`b` memory location: 4303023376
